apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-nwupeedt
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-nwupeedt:20dab1d2dd4762156331215cd5e6ae2fb9b5576a@sha256:97e64293801e6a8245feb4bd17f033f348bf59b0696ed507fedd5bf1c96fbec2
          name: container-image
