apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-nwupeedt
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-nwupeedt:0498dcf6c60f19caa7b9b8b4f01ee5a1f0f2f15e@sha256:812296a42470dc5aa5998954486cf172c065644f04280db2c6faf273bc2c0c0c
          name: container-image
